Traceback (most recent call last):
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 22, in <module>
    main()
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 22, in <module>
    main()
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 22, in <module>
    main()
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 22, in <module>
    main()
  File "/Users/jjpark987/Desktop/sentiment_analysis/backend/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Watching for file changes with StatReloader
Not Found: /
[13/Jun/2024 02:26:05] "GET / HTTP/1.1" 404 2164
[13/Jun/2024 02:26:09] "GET /admin/ HTTP/1.1" 200 7438
Watching for file changes with StatReloader
